<?xml version="1.0" encoding="utf-8"?>
<robot name="matrobot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="mesh_root" value="$(find matrobot_description)/meshes"/>
  <!--mesh filename="file://${mesh_root}/base_link.STL" /--> <!--urdf oluşturduktan sonra visual kısma ekle-->

  <static>false</static>

  <!-- Properties -->
  <xacro:include filename="$(find matrobot_description)/urdf/properties.xacro" />
  <xacro:arg name="use_gazebo" default="false"/>
  
  <xacro:property name="base_width" value="0.34" />
  <xacro:property name="base_length" value="0.4" />
  <xacro:property name="base_height" value="0.11" />
  <xacro:property name="base_weight" value="5.0" />

  <xacro:property name="wheel_radius" value="0.09" />
  <xacro:property name="wheel_length" value="0.05" />
  <xacro:property name="wheel_weight" value="1.0" />

  <xacro:property name="caster_wheel_radius" value="${(wheel_radius - (base_height / 2)) / 2}" />
  <xacro:property name="caster_wheel_weight" value="0.5" />
  
  <xacro:property name="wheel_separation" value="${base_width + wheel_length + 0.08}" />  <!--Gövde genişliği + (Teker genişliği/2)*2 + mil uzunluğu-->
  <xacro:property name="wheel_diameter" value="${wheel_radius}" />

  <xacro:property name="lidar_radius" value="0.0275"/>
  <xacro:property name="lidar_height" value="0.04"/>
  <xacro:property name="lidar_mass" value="0.115"/>

  <!-- Base Link -->
  <link name="base_footprint"/>
  <link name="base_link">
    <xacro:box_inertia m="${base_weight}" l="${base_length}" w="${base_width}" h="${base_height}"
                        xyz="0 0 0" rpy="0 0 0"/>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="Black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
  </link>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 0.09" rpy="0 0 0"/>
  </joint>   

  <!-- Wheels -->
  <xacro:macro name="Wheel_Link" params="name parent_link x y z">
    <link name="${name}_link">
      <xacro:cylinder_inertia m="${wheel_weight}" r="${wheel_radius}" h="${wheel_length}" xyz="0 0 0" rpy="0 0 0"/>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <surface>
          <friction>
            <ode>
              <mu>1.5</mu>
              <mu2>1.5</mu2>
            </ode>
          </friction>
        </surface>
      </collision>
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        <material name="Red">
          <color rgba="0.75 0 0 1"/>
        </material>
      </visual>
    </link>
    <joint name="${name}_joint" type="continuous">
      <parent link="${parent_link}"/>
      <child link="${name}_link"/>
      <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit effort="5.0" velocity="6.3"/>
      <dynamics damping="0.1" friction="0.01"/>
    </joint>
  </xacro:macro>

  <!-- Caster Wheel -->
  <xacro:macro name="Caster_Wheel" params="name parent_link x y z">
    <link name="${name}_link">
      <xacro:sphere_inertia m="${caster_wheel_weight}" r="${caster_wheel_radius}" xyz="0 0 0" rpy="0 0 0"/>
      <collision>
        <geometry>
          <sphere radius="${caster_wheel_radius}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </collision>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_wheel_radius}"/>
        </geometry>
        <material name="Gray">
          <color rgba="0.75 0.75 0.75 1"/>
        </material>
      </visual>
    </link>
    <joint name="${name}_joint" type="fixed">
      <parent link="${parent_link}"/>
      <child link="${name}_link"/>
      <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>
  <!-- LIDAR Link & Joint -->
  <link name="lidar_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find matrobot_description)/meshes/LIDAR.STL"/>
      </geometry>
      <material name="Gray">
        <color rgba="0.75 0.75 0.75 1"/>
      </material>
    </visual>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="${(base_length / 2) - 0.05} 0 ${(base_height / 2) +0.05}" rpy="0 0 0"/>
  </joint>

  <!-- IMU Link & Joint -->
  <link name="imu_link"/>
  <joint name="imu_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="imu_link" />
    <axis xyz="0 1 0" />
  </joint>
  
  <!-- Instantiate all links -->
  <xacro:Wheel_Link name="left_wheel"  parent_link="base_link"
                    x="-${((base_width + wheel_length) / 2) - 0.05}"
                    y="${(base_width + wheel_length) / 2}" z="0.0"/>

  <xacro:Wheel_Link name="right_wheel" parent_link="base_link"
                    x="-${((base_width + wheel_length) / 2) - 0.05}"
                    y="-${(base_width + wheel_length) / 2}" z="0.0"/>

  <xacro:Caster_Wheel name="caster_front_wheel" parent_link="base_link"
                      x="${(base_length / 2) - 0.02}" y="0.0"
                      z="-${((wheel_radius + (base_height / 2)) / 2 )}"/>   
                      
	<!-- Gazebo visual / friction settings -->
	<xacro:macro name="gazebo_visual_settings" params="link_name color_name">
	  <gazebo reference="${link_name}">
	    <material>${color_name}</material>
	    <mu1>1.5</mu1>
	    <mu2>1.5</mu2>
	  </gazebo>
	</xacro:macro>       
	<xacro:if value="$(arg use_gazebo)">
		<gazebo reference="lidar_link">
		  <sensor name="rplidar_s1" type="gpu_lidar">
		    <always_on>true</always_on>
		    <update_rate>10</update_rate>
		    <gz_frame_id>lidar_link</gz_frame_id>
		    <topic>/scan</topic>
		    <lidar>
		      <scan>
		        <horizontal>
		          <samples>1200</samples>
		          <resolution>1</resolution>
		          <min_angle>-3.14159</min_angle>
		          <max_angle>3.14159</max_angle>
		        </horizontal>
		        <vertical>
		          <samples>1</samples>
		          <min_angle>0</min_angle>
		          <max_angle>0</max_angle>
		        </vertical>
		      </scan>
		      <range>
		        <min>0.15</min>
		        <max>40.0</max>
		        <resolution>0.01</resolution>
		      </range>
		    </lidar>
		    <!-- Ogre crash riskini azaltmak için -->
		    <visualize>false</visualize>
		  </sensor>
		</gazebo>

		<gazebo reference="imu_link">
		  <sensor name="imu_sensor" type="imu">
		    <always_on>1</always_on>
		    <update_rate>50</update_rate>
		    <topic>/imu/data</topic>
		    <gz_frame_id>imu_link</gz_frame_id>
		    <imu>
		      <enable_orientation>1</enable_orientation>

		      <angular_velocity>
		        <x>
		          <noise type="gaussian">
		            <mean>0</mean>
		            <stddev>0.009</stddev>
		            <bias_mean>0.00075</bias_mean>
		            <bias_stddev>0.005</bias_stddev>
		            <dynamic_bias_stddev>0.00002</dynamic_bias_stddev>
		            <dynamic_bias_correlation_time>400.0</dynamic_bias_correlation_time>
		            <precision>0.00025</precision>
		          </noise>
		        </x>
		        <y>
		          <noise type="gaussian">
		            <mean>0</mean>
		            <stddev>0.009</stddev>
		            <bias_mean>0.00075</bias_mean>
		            <bias_stddev>0.005</bias_stddev>
		            <dynamic_bias_stddev>0.00002</dynamic_bias_stddev>
		            <dynamic_bias_correlation_time>400.0</dynamic_bias_correlation_time>
		            <precision>0.00025</precision>
		          </noise>
		        </y>
		        <z>
		          <noise type="gaussian">
		            <mean>0</mean>
		            <stddev>0.009</stddev>
		            <bias_mean>0.00075</bias_mean>
		            <bias_stddev>0.005</bias_stddev>
		            <dynamic_bias_stddev>0.00002</dynamic_bias_stddev>
		            <dynamic_bias_correlation_time>400.0</dynamic_bias_correlation_time>
		            <precision>0.00025</precision>
		          </noise>
		        </z>
		      </angular_velocity>

		      <linear_acceleration>
		        <x>
		          <noise type="gaussian">
		            <mean>0</mean>
		            <stddev>0.021</stddev>
		            <bias_mean>0.05</bias_mean>
		            <bias_stddev>0.0075</bias_stddev>
		            <dynamic_bias_stddev>0.000375</dynamic_bias_stddev>
		            <dynamic_bias_correlation_time>175.0</dynamic_bias_correlation_time>
		            <precision>0.005</precision>
		          </noise>
		        </x>
		        <y>
		          <noise type="gaussian">
		            <mean>0</mean>
		            <stddev>0.021</stddev>
		            <bias_mean>0.05</bias_mean>
		            <bias_stddev>0.0075</bias_stddev>
		            <dynamic_bias_stddev>0.000375</dynamic_bias_stddev>
		            <dynamic_bias_correlation_time>175.0</dynamic_bias_correlation_time>
		            <precision>0.005</precision>
		          </noise>
		        </y>
		        <z>
		          <noise type="gaussian">
		            <mean>0</mean>
		            <stddev>0.021</stddev>
		            <bias_mean>0.05</bias_mean>
		            <bias_stddev>0.0075</bias_stddev>
		            <dynamic_bias_stddev>0.000375</dynamic_bias_stddev>
		            <dynamic_bias_correlation_time>175.0</dynamic_bias_correlation_time>
		            <precision>0.005</precision>
		          </noise>
		        </z>
		      </linear_acceleration>
		    </imu>
		  </sensor>
		</gazebo>
		<!-- DiffDrive plugin -->
		<gazebo>
		  <plugin filename="gz-sim-diff-drive-system"
		          name="gz::sim::systems::DiffDrive">
		    <update_rate>20</update_rate>

		    <left_joint>left_wheel_joint</left_joint>
		    <right_joint>right_wheel_joint</right_joint>

		    <wheel_separation>${wheel_separation}</wheel_separation>
		    <wheel_radius>${wheel_radius}</wheel_radius>

		    <topic>/cmd_vel</topic>

		    <odom_topic>/odometry/wheel</odom_topic>
		    <odom_publish_frequency>50</odom_publish_frequency>

		    <frame_id>odom</frame_id>
		    <child_frame_id>base_footprint</child_frame_id>
		  </plugin>
		</gazebo>
		
		<!-- JointStatePublisher plugin -->
		<gazebo>
		  <plugin filename="gz-sim-joint-state-publisher-system"
		          name="gz::sim::systems::JointStatePublisher">
		    <topic>/joint_states</topic>
		  </plugin>
		</gazebo>
		<xacro:gazebo_visual_settings link_name="base_link"       color_name="Gazebo/Black" />
		<xacro:gazebo_visual_settings link_name="left_wheel_link"  color_name="Gazebo/Red" />
		<xacro:gazebo_visual_settings link_name="right_wheel_link" color_name="Gazebo/Red" />
	</xacro:if>
</robot>
